# frozen_string_literal: true

# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = Rails.application.credentials[:MAIL_JET]
  config.secret_key = Rails.application.credentials[:MAIL_JET_SECRET]
  config.default_from = 'mathieu.maillet@ymail.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
variable = Mailjet::Send.create(
    from_email: "mathieu.maillet@ymail.com",
    from_name: "Mailjet Pilot",
    subject: "Your email flight plan!",
    text_part: "Dear passenger, welcome to Mailjet! May the delivery force be with you!",
    html_part: "<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!",
    recipients: [{ 'Email'=> 'passenger@mailjet.com'}]
)
